UI Elements
nate3323/GROW pull request #12
Opened 2024-05-30 22:49 UTC by SgtKrieg

Quit Button, Settings Button, Wave number, currency, and enemy count labels.

2024-06-03 17:56 UTC, wolfyman411 requested changes
Enemy counter throws an error since it can't find any enemies, the quit button is in the middle of the screen and needs to be move into an area that isn't going to affect gameplay. Branch is using a very old build, I'd recommend updating it and making sure that your code works.

Wave counter also currently doesn't have any code in it, this needs to have functionality as it should be possible in the newer builds to access the current wave number.

2024-06-03 17:56 UTC, wolfyman411 commented on CELL TD/Assets/Scripts/UI/EnemyCounter.cs
> +        enemies = GameObject.FindGameObjectsWithTag("Enemy");
In an updated build we have something that already keeps track of how many enemies there are. Use that instead of this.

2024-06-03 17:56 UTC, wolfyman411 commented on CELL TD/Assets/Scripts/UI/QuitGame.cs
> +        Application.Quit();
This should take you back to the level selector instead of quitting the game, please update the branch to have access to the scenes.

2024-06-18 18:08 UTC, SgtKrieg commented
Already fixed these issues

2024-06-20 16:07 UTC, wolfyman411 requested changes
-Enemy counter works only for the first wave, after that the counter starts providing incorrect information, and even goes into the negatives.

2024-06-21 18:13 UTC, merged